# Generated by Django 5.0.6 on 2024-06-22 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_menuitem_category_remove_address_zip_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
