# Generated by Django 5.0.6 on 2024-06-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
