# Generated by Django 5.0.6 on 2024-06-24 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_delete_customuser_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
