# Generated by Django 5.0.6 on 2024-06-24 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_userprofile_user_remove_address_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_addresses', to='user.user'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
