# Generated by Django 5.0.6 on 2024-06-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='customer_orders',
        ),
    ]
