# Generated by Django 5.0.6 on 2024-07-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_rename_id_menuitem_menu_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.ManyToManyField(related_name='restaurants', to='restaurant.address'),
        ),
    ]
