# Generated by Django 5.0.6 on 2024-07-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurant_average_cost_restaurant_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='preparation_time',
            field=models.IntegerField(default=30),
        ),
    ]
