# Generated by Django 5.0.6 on 2024-07-02 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_restaurant_address_restaurant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='restaurant_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_addresses', to='restaurant.restaurant'),
        ),
    ]
