# Generated by Django 5.0.6 on 2024-07-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_menuitem_preparation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_visible_to_restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
