# Generated by Django 5.0.7 on 2024-07-18 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_order_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
    ]
