# Generated by Django 5.0.7 on 2024-07-26 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_menuitem_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='user',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryPerson',
        ),
    ]
