# Generated by Django 5.0.6 on 2024-07-04 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_cartitem_quantity'),
        ('restaurant', '0010_remove_restaurant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.address'),
        ),
    ]
