# Generated by Django 5.0.6 on 2024-07-07 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
