# Generated by Django 5.0.6 on 2024-07-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_remove_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
