# Generated by Django 5.0.6 on 2024-07-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_menuitem_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
