# Generated by Django 5.0.6 on 2024-07-14 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='restaurant.restaurant')),
            ],
        ),
    ]
