# Generated by Django 5.0.6 on 2024-07-14 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_restaurantanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantanalysis',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='restaurant.restaurant'),
        ),
    ]
