from django.urls import path, include
from . import views
from django.contrib.auth.views import LogoutView


urlpatterns = [
 path('home/', views.home, name='home'),
 path('', views.home, name='home'),
path('location/', views.location, name='location'),
path('landing/', views.landing, name='landing'),
path('food-home/', views.food_home, name='food-home'),
path('grocery-home/', views.grocery_home, name='grocery-home'),
path('pharmacy-home/', views.pharmacy_home, name='pharmacy-home'),
path('profile', views.profile, name='profile'),
path('profile-settings', views.profile_settings, name='profile-settings'),
path('manage-delivery-address', views.manage_delivery_address, name='manage-delivery-address'),
path('wishlist', views.wishlist, name='wishlist'),
path('manage-payment', views.manage_payment, name='manage-payment'),
path('order-history', views.order_history, name='order-history'),
path('voucher', views.voucher, name='voucher'),
path('app-setting', views.app_setting, name='app-setting'),
path('notification-setting', views.notification_setting, name='notification-setting'),
path('logout/', LogoutView.as_view(), name='logout'),
path('details/', views.details, name='details'),
path('cart/', views.cart, name='cart'),
path('coupon/', views.coupon, name='coupon'),
path('address/', views.address, name='address'),
path('confirm-location/', views.confirm_location, name='confirm-location'),
path('payment-method/', views.payment_method, name='payment-method'),
path('new-card/', views.new_card, name='new-card'),
path('order-tracking/', views.order_tracking, name='order-tracking'),
path('order-details/', views.order_details, name='order-details'),
path('chatting', views.chatting, name='chatting'),
path('page-listing/', views.page_listing, name='page-listing'),
path('onboarding', views.onboarding, name='onboarding'),
path('otp', views.otp, name='otp'),
path('listing', views.listing, name='listing'),
path('brand-list', views.brand_list, name='brand-list'),
path('categories', views.categories, name='categories'),
path('address-details', views.address_details, name='address-details'),
path('offer', views.offer, name='offer'),
path('notification', views.notification, name='notification'),
path('other-setting', views.other_setting, name='other-setting'),
path('empty-cart', views.empty_cart, name='empty-cart'),
path('empty-wishlist', views.empty_wishlist, name='empty-wishlist'),
path('empty-notification', views.empty_notification, name='empty-notification'),
path('empty-search', views.empty_search, name='empty-search'),
path('search', views.search, name='search'),
]

